version: '3.3'
services:
  mysql:
    container_name: MySQL
    restart: unless-stopped
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: db
      MYSQL_USER: raz
      MYSQL_PASSWORD: test_password
      MYSQL_ROOT_PASSWORD: test_password
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

      
  postgres:
    container_name: PostgreSQL
    restart: unless-stopped
    image: postgres
    environment: 
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: test_db
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data/ # persist data even if container shuts down

  mongo:
    container_name: MongoDB
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: test_user
      MONGO_INITDB_ROOT_PASSWORD: test_password
    ports:
      - '27017:27017'

  redis:
    container_name: Redis
    restart: unless-stopped
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  cassandra:
    container_name: Cassandra # Default username and pass: cassandra
    restart: unless-stopped
    image: cassandra
    ports:
      - '9042:9042'
    volumes:
      - cassandra-data:/var/lib/cassandra


volumes:
  postgres-data: 
  mysql-data:
  redis-data:
  cassandra-data: