version: '3.3'
services:
  mysql:
    container_name: MySQL
    restart: unless-stopped
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: $DEFAULT_DATABASE
      MYSQL_USER: $DEFAULT_USERNAME
      MYSQL_PASSWORD: $DEFAULT_PASSWORD
      MYSQL_ROOT_PASSWORD: $DEFAULT_PASSWORD
    ports:
      - '3306:3306'
    volumes:
      - mysql-data:/var/lib/mysql

      
  postgres:
    container_name: PostgreSQL
    restart: unless-stopped
    image: postgres
    environment: 
      POSTGRES_USER: $DEFAULT_USERNAME
      POSTGRES_PASSWORD: $DEFAULT_PASSWORD
      POSTGRES_DB: $DEFAULT_DATABASE
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data/ # persist data even if container shuts down

  mongo:
    container_name: MongoDB
    image: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: $DEFAULT_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $DEFAULT_PASSWORD
    ports:
      - '27017:27017'

  redis:
    container_name: Redis
    restart: unless-stopped
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  cassandra:
    container_name: Cassandra # Default username and pass: cassandra
    restart: unless-stopped
    image: cassandra
    ports:
      - '9042:9042'
    volumes:
      - cassandra-data:/var/lib/cassandra

  neo4j:
    container_name: Neo4j
    restart: unless-stopped
    image: neo4j
    ports:
      - '7474:7474'
      - '7687:7687'
    environment:
      NEO4J_AUTH: neo4j/$DEFAULT_PASSWORD
    volumes:
      - neo4j-data:/data

volumes:
  postgres-data: 
  mysql-data:
  redis-data:
  cassandra-data:
  neo4j-data: